package jsonschema

import (
	"encoding/json"
	"fmt"
	"go/format"
	"maps"
	"sort"
	"strings"
)

// GoOption configures schema-to-Go-types generation. Pass options to
// [GenerateGo] or [NewGoGenerator].
type GoOption func(*goOptions)

// goOptions is the resolved configuration for a generation run.
type goOptions struct {
	pkg      string
	rootType string
	header   string
}

// defaultGoHeader is the banner placed atop generated files. It matches the
// conventional generated-code marker so tooling (and humans) skip the file.
const defaultGoHeader = "Code generated by jsonschema; DO NOT EDIT."

// defaultGoOptions returns the baseline configuration before options apply.
func defaultGoOptions() goOptions {
	return goOptions{pkg: "models", rootType: "", header: defaultGoHeader}
}

// WithGoPackage sets the package name declared by the generated file. The
// default is "models".
func WithGoPackage(name string) GoOption {
	return func(o *goOptions) { o.pkg = name }
}

// WithGoRootType sets the name of the generated root type. When empty (the
// default), the name is derived from the schema's "title", falling back to
// "Root".
func WithGoRootType(name string) GoOption {
	return func(o *goOptions) { o.rootType = name }
}

// WithGoHeaderComment sets the banner comment placed at the top of the
// generated file. An empty string omits the banner entirely.
func WithGoHeaderComment(text string) GoOption {
	return func(o *goOptions) { o.header = text }
}

// GoGenerator is the configurable schema-to-Go-types worker. Reuse a single
// GoGenerator to render many schemas with the same options; option parsing
// happens once at construction. It is the inverse of [Generator], which
// produces a schema from a Go type.
type GoGenerator struct {
	opts goOptions
}

// NewGoGenerator returns a GoGenerator with opts applied. Unset options keep
// their documented defaults.
func NewGoGenerator(opts ...GoOption) *GoGenerator {
	o := defaultGoOptions()
	for _, opt := range opts {
		opt(&o)
	}
	return &GoGenerator{opts: o}
}

// GenerateGo parses schemaJSON and returns gofmt-formatted Go source that
// declares a struct for the schema's root object plus a named type for every
// entry under "definitions" / "$defs". It is a convenience wrapper over
// NewGoGenerator(opts...).Generate.
func GenerateGo(schemaJSON []byte, opts ...GoOption) ([]byte, error) {
	return NewGoGenerator(opts...).Generate(schemaJSON)
}

// MustGenerateGo is the panic-on-error variant of [GenerateGo], intended for
// code-generation programs and tests over static, known-good schemas.
func MustGenerateGo(schemaJSON []byte, opts ...GoOption) []byte {
	src, err := GenerateGo(schemaJSON, opts...)
	if err != nil {
		panic(err)
	}
	return src
}

// Generate parses schemaJSON and returns gofmt-formatted Go source. The
// schema is compiled first (and thereby validated): a malformed schema
// yields an error rather than partial output.
func (g *GoGenerator) Generate(schemaJSON []byte) ([]byte, error) {
	if _, err := Compile(schemaJSON); err != nil {
		return nil, fmt.Errorf("compile schema: %w", err)
	}

	var root map[string]any
	if err := json.Unmarshal(schemaJSON, &root); err != nil {
		return nil, fmt.Errorf("decode schema document: %w", err)
	}

	b := &goBuilder{opts: g.opts, seen: map[string]bool{}}
	rootName := b.rootName(root)
	b.defineType(rootName, stringOf(root["description"]), root)

	defs := definitions(root)
	for _, name := range sortedKeys(defs) {
		def := mapOf(defs[name])
		b.defineType(name, stringOf(def["description"]), def)
	}

	formatted, err := format.Source(b.render(rootName))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

// goBuilder accumulates the type declarations discovered while walking a
// schema. Inline object schemas are hoisted into named types as they are
// encountered; seen guards against re-defining or infinitely recursing.
type goBuilder struct {
	opts  goOptions
	decls []typeDecl
	seen  map[string]bool
}

// typeDecl is one generated type: either a struct (fields/embeds) or, for a
// non-object schema, a type alias to the expression in alias.
type typeDecl struct {
	name   string
	doc    string
	alias  string
	embeds []string
	fields []fieldDecl
}

// fieldDecl is one struct field: its Go name, type expression, json tag
// body, and optional doc comment.
type fieldDecl struct {
	name string
	typ  string
	tag  string
	doc  string
}

// rootName resolves the name of the document's root type from the option,
// the schema's title, or the "Root" fallback.
func (b *goBuilder) rootName(root map[string]any) string {
	if b.opts.rootType != "" {
		return b.opts.rootType
	}
	if name := exportedName(stringOf(root["title"])); name != "" {
		return name
	}
	return "Root"
}

// defineType registers one named type derived from schema sch. Objects (and
// allOf compositions) become structs; everything else becomes a type alias.
func (b *goBuilder) defineType(name, doc string, sch map[string]any) {
	if name == "" || b.seen[name] {
		return
	}
	b.seen[name] = true

	_, hasProps := sch["properties"]
	allOf, hasAllOf := sch["allOf"].([]any)
	if !hasProps && !hasAllOf {
		alias, _ := b.goType(sch, name)
		b.decls = append(b.decls, typeDecl{name: name, doc: doc, alias: alias})
		return
	}

	embeds, props, required := b.collectFields(sch, allOf, hasAllOf)
	decl := typeDecl{name: name, doc: doc, embeds: embeds}
	keys := sortedKeys(props)
	decl.fields = make([]fieldDecl, 0, len(keys))
	for _, key := range keys {
		ps := mapOf(props[key])
		typ, isObj := b.goType(ps, name+fieldName(key))
		if isObj && !required[key] {
			typ = "*" + typ
		}
		decl.fields = append(decl.fields, fieldDecl{
			name: fieldName(key),
			typ:  typ,
			tag:  jsonTag(key, required[key]),
			doc:  stringOf(ps["description"]),
		})
	}
	b.decls = append(b.decls, decl)
}

// collectFields gathers the embedded base types, merged property set, and
// required-name set for a struct. allOf $refs become embeds; inline allOf
// objects (and the plain non-allOf case) contribute their properties.
func (b *goBuilder) collectFields(sch map[string]any, allOf []any, hasAllOf bool) (embeds []string, props map[string]any, required map[string]bool) {
	props = map[string]any{}
	required = map[string]bool{}
	if !hasAllOf {
		maps.Copy(props, mapOf(sch["properties"]))
		addRequired(required, sch["required"])
		return embeds, props, required
	}
	embeds = make([]string, 0, len(allOf))
	for _, raw := range allOf {
		sub := mapOf(raw)
		if ref, ok := sub["$ref"].(string); ok {
			embeds = append(embeds, refName(ref))
			continue
		}
		maps.Copy(props, mapOf(sub["properties"]))
		addRequired(required, sub["required"])
	}
	return embeds, props, required
}

// goType maps a property or value schema to a Go type expression. The second
// result reports whether the type names an object, so callers can make an
// optional occurrence a pointer.
func (b *goBuilder) goType(sch map[string]any, hint string) (string, bool) {
	if ref, ok := sch["$ref"].(string); ok {
		return refName(ref), true
	}
	if _, ok := sch["properties"]; ok {
		b.defineType(hint, stringOf(sch["description"]), sch)
		return hint, true
	}
	if _, ok := sch["allOf"]; ok {
		b.defineType(hint, stringOf(sch["description"]), sch)
		return hint, true
	}
	switch typeName(sch) {
	case "string":
		return "string", false
	case "integer":
		return "int", false
	case "number":
		return "float64", false
	case "boolean":
		return "bool", false
	case "array":
		return "[]" + b.elemType(sch, hint), false
	case "object":
		return b.mapType(sch, hint), false
	}
	if t := enumType(sch); t != "" {
		return t, false
	}
	return "any", false
}

// elemType returns the Go element type for an array schema, hoisting an
// inline item object when necessary.
func (b *goBuilder) elemType(sch map[string]any, hint string) string {
	items, ok := sch["items"].(map[string]any)
	if !ok {
		return "any"
	}
	typ, _ := b.goType(items, hint+"Item")
	return typ
}

// mapType returns the Go type for an object schema without declared
// properties: a map keyed by string whose value type comes from
// additionalProperties, or map[string]any when that is absent.
func (b *goBuilder) mapType(sch map[string]any, hint string) string {
	if ap, ok := sch["additionalProperties"].(map[string]any); ok {
		typ, _ := b.goType(ap, hint+"Value")
		return "map[string]" + typ
	}
	if pp, ok := sch["patternProperties"].(map[string]any); ok && len(pp) > 0 {
		return "map[string]" + b.patternValueType(pp, hint)
	}
	return "map[string]any"
}

// patternValueType returns the Go value type shared by every
// patternProperties subschema, or "any" when they disagree or are empty.
func (b *goBuilder) patternValueType(pp map[string]any, hint string) string {
	common := ""
	for _, key := range sortedKeys(pp) {
		typ, _ := b.goType(mapOf(pp[key]), hint+"Value")
		switch {
		case common == "":
			common = typ
		case common != typ:
			return "any"
		}
	}
	if common == "" {
		return "any"
	}
	return common
}

// render orders the accumulated declarations (root first, then alphabetical)
// and writes the complete, unformatted source file.
func (b *goBuilder) render(rootName string) []byte {
	sort.SliceStable(b.decls, func(i, j int) bool {
		switch {
		case b.decls[i].name == rootName:
			return true
		case b.decls[j].name == rootName:
			return false
		default:
			return b.decls[i].name < b.decls[j].name
		}
	})

	var sb strings.Builder
	if b.opts.header != "" {
		fmt.Fprintf(&sb, "// %s\n\n", b.opts.header)
	}
	fmt.Fprintf(&sb, "package %s\n", b.opts.pkg)
	for i := range b.decls {
		sb.WriteByte('\n')
		writeDecl(&sb, b.decls[i])
	}
	return []byte(sb.String())
}

// writeDecl writes a single type declaration (struct or alias) to sb.
func writeDecl(sb *strings.Builder, d typeDecl) {
	sb.WriteString(comment("", d.doc))
	if d.alias != "" {
		fmt.Fprintf(sb, "type %s %s\n", d.name, d.alias)
		return
	}
	fmt.Fprintf(sb, "type %s struct {\n", d.name)
	for _, e := range d.embeds {
		fmt.Fprintf(sb, "\t%s\n", e)
	}
	for i := range d.fields {
		f := d.fields[i]
		sb.WriteString(comment("\t", f.doc))
		fmt.Fprintf(sb, "\t%s %s `json:%q`\n", f.name, f.typ, f.tag)
	}
	sb.WriteString("}\n")
}

// definitions merges the schema's "definitions" and "$defs" maps into one.
func definitions(root map[string]any) map[string]any {
	out := map[string]any{}
	maps.Copy(out, mapOf(root["definitions"]))
	maps.Copy(out, mapOf(root["$defs"]))
	return out
}

// typeName returns the schema's "type" as a single name. A type array such
// as ["string","null"] resolves to its sole non-null member; a union of
// several concrete types resolves to the empty string (meaning "any").
func typeName(sch map[string]any) string {
	switch t := sch["type"].(type) {
	case string:
		return t
	case []any:
		found := ""
		for _, e := range t {
			s, ok := e.(string)
			if !ok || s == "null" {
				continue
			}
			if found != "" {
				return ""
			}
			found = s
		}
		return found
	default:
		return ""
	}
}

// enumType infers a Go type from an enum or const value when no explicit
// type keyword is present. It returns the empty string when neither applies.
func enumType(sch map[string]any) string {
	if vals, ok := sch["enum"].([]any); ok && len(vals) > 0 {
		return scalarType(vals[0])
	}
	if c, ok := sch["const"]; ok {
		return scalarType(c)
	}
	return ""
}

// scalarType maps a decoded JSON scalar to its Go type.
func scalarType(v any) string {
	switch v.(type) {
	case string:
		return "string"
	case bool:
		return "bool"
	case float64, json.Number:
		return "float64"
	default:
		return "any"
	}
}

// jsonTag returns the json struct-tag body for a property: bare for required
// fields, with ",omitempty" otherwise.
func jsonTag(key string, required bool) string {
	if required {
		return key
	}
	return key + ",omitempty"
}

// refName returns the trailing segment of a JSON-pointer $ref, e.g.
// "#/definitions/Command" becomes "Command".
func refName(ref string) string {
	if i := strings.LastIndex(ref, "/"); i >= 0 {
		return ref[i+1:]
	}
	return ref
}

// fieldName converts a JSON property key to an exported Go identifier:
// "$schema" becomes "Schema", "gen_file" becomes "GenFile".
func fieldName(key string) string {
	return exportedName(strings.TrimPrefix(key, "$"))
}

// exportedName converts an arbitrary label to a PascalCase Go identifier,
// splitting on any non-alphanumeric run. It returns the empty string when no
// usable identifier can be formed.
func exportedName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return false
		default:
			return true
		}
	})
	var sb strings.Builder
	for _, p := range parts {
		sb.WriteString(strings.ToUpper(p[:1]))
		sb.WriteString(p[1:])
	}
	out := sb.String()
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		return ""
	}
	return out
}

// comment renders text as a doc-comment block at the given indent, one line
// per source line. Empty text yields nothing.
func comment(indent, text string) string {
	if text == "" {
		return ""
	}
	var sb strings.Builder
	for line := range strings.SplitSeq(text, "\n") {
		fmt.Fprintf(&sb, "%s// %s\n", indent, line)
	}
	return sb.String()
}

// mapOf coerces v to a map[string]any, returning an empty map when v is
// absent or not an object.
func mapOf(v any) map[string]any {
	m, _ := v.(map[string]any)
	return m
}

// stringOf coerces v to a string, returning "" when v is absent or not a
// string.
func stringOf(v any) string {
	s, _ := v.(string)
	return s
}

// addRequired adds the string elements of a JSON array to set.
func addRequired(set map[string]bool, v any) {
	arr, _ := v.([]any)
	for _, e := range arr {
		if s, ok := e.(string); ok {
			set[s] = true
		}
	}
}

// sortedKeys returns the keys of m in lexical order for deterministic output.
func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
