package jsonschema_test

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"strings"
	"testing"

	"github.com/go-rotini/jsonschema"
)

// parseGo fails the test unless src is syntactically valid Go.
func parseGo(t *testing.T, src []byte) {
	t.Helper()
	if _, err := parser.ParseFile(token.NewFileSet(), "gen.go", src, parser.AllErrors); err != nil {
		t.Fatalf("generated source is not valid Go: %v\n---\n%s", err, src)
	}
}

// flat collapses all runs of whitespace to single spaces so substring
// assertions don't depend on gofmt's column alignment.
func flat(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func mustContain(t *testing.T, src []byte, wants ...string) {
	t.Helper()
	got := flat(string(src))
	for _, w := range wants {
		if !strings.Contains(got, flat(w)) {
			t.Errorf("generated source missing %q\n---\n%s", w, src)
		}
	}
}

func TestGenerateGo_basicStruct(t *testing.T) {
	schema := []byte(`{
		"title": "Person",
		"type": "object",
		"required": ["name"],
		"properties": {
			"name": {"type": "string", "description": "full name"},
			"age": {"type": "integer"},
			"tags": {"type": "array", "items": {"type": "string"}}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema, jsonschema.WithGoPackage("people"))
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src,
		"package people",
		"// Code generated by jsonschema; DO NOT EDIT.",
		"type Person struct",
		"// full name",
		"Name string `json:\"name\"`",
		"Age int `json:\"age,omitempty\"`",
		"Tags []string `json:\"tags,omitempty\"`",
	)
}

func TestGenerateGo_refsDefinitionsAndPointers(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"properties": {
			"inputs": {"$ref": "#/definitions/Inputs"},
			"names": {"type": "object", "additionalProperties": {"type": "string"}}
		},
		"definitions": {
			"Inputs": {
				"type": "object",
				"required": ["flag"],
				"properties": {
					"flag": {"type": "boolean"},
					"count": {"type": "number"}
				}
			}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema, jsonschema.WithGoRootType("Doc"))
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src,
		"type Doc struct",
		"Inputs *Inputs `json:\"inputs,omitempty\"`", // optional object ref -> pointer
		"Names map[string]string `json:\"names,omitempty\"`",
		"type Inputs struct",
		"Flag bool `json:\"flag\"`", // required -> no omitempty
		"Count float64 `json:\"count,omitempty\"`",
	)
}

func TestGenerateGo_allOfEmbedding(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"definitions": {
			"Base": {
				"type": "object",
				"properties": {"kind": {"type": "string"}}
			},
			"Derived": {
				"allOf": [
					{"$ref": "#/definitions/Base"},
					{"type": "object", "properties": {"extra": {"type": "string"}}}
				]
			}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema)
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src,
		"type Base struct",
		"type Derived struct { Base", // Base embedded ahead of own fields
		"Extra string `json:\"extra,omitempty\"`",
	)
}

func TestGenerateGo_invalidSchema(t *testing.T) {
	if _, err := jsonschema.GenerateGo([]byte("not a schema")); err == nil {
		t.Fatal("expected error for malformed schema, got nil")
	}
}

func ExampleGenerateGo() {
	schema := []byte(`{
		"title": "Point",
		"type": "object",
		"properties": {"x": {"type": "number"}, "y": {"type": "number"}}
	}`)
	src, err := jsonschema.GenerateGo(schema)
	if err != nil {
		fmt.Println("error:", err)
		return
	}
	fmt.Println(strings.Contains(string(src), "type Point struct"))
	// Output: true
}

// structFieldType parses src and returns the Go type expression of
// structName.fieldName, as rendered by go/types.ExprString.
func structFieldType(t *testing.T, src []byte, structName, fieldName string) string {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), "gen.go", src, 0)
	if err != nil {
		t.Fatalf("parse generated source: %v\n%s", err, src)
	}
	got := ""
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != structName {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		for _, fld := range st.Fields.List {
			if len(fld.Names) == 1 && fld.Names[0].Name == fieldName {
				got = types.ExprString(fld.Type)
			}
		}
		return false
	})
	if got == "" {
		t.Fatalf("field %s.%s not found in:\n%s", structName, fieldName, src)
	}
	return got
}

// optionalFieldType generates types for a single optional "field" property
// described by propSchema and returns that field's Go type. A "Ref" object
// definition is always available for $ref cases.
func optionalFieldType(t *testing.T, propSchema string) string {
	t.Helper()
	schema := `{
		"$schema": "http://json-schema.org/draft-07/schema#",
		"type": "object",
		"definitions": {"Ref": {"type": "object", "properties": {"a": {"type": "string"}}}},
		"properties": {"field": ` + propSchema + `}
	}`
	src, err := jsonschema.GenerateGo([]byte(schema), jsonschema.WithGoRootType("Root"))
	if err != nil {
		t.Fatalf("GenerateGo(%s): %v", propSchema, err)
	}
	return structFieldType(t, src, "Root", "Field")
}

// TestGenerateGo_typeMatrix exercises the type mapping across the full range
// of JSON Schema constructs the generator recognizes, plus the constructs it
// deliberately degrades to any (unions, oneOf/anyOf/not, conditionals,
// boolean schemas, empty schemas). Fields here are optional, so scalars are
// value types and object references are pointers.
func TestGenerateGo_typeMatrix(t *testing.T) {
	cases := []struct {
		name string
		prop string
		want string
	}{
		// Scalars.
		{"string", `{"type":"string"}`, "string"},
		{"integer", `{"type":"integer"}`, "int"},
		{"number", `{"type":"number"}`, "float64"},
		{"boolean", `{"type":"boolean"}`, "bool"},

		// Arrays.
		{"array_of_string", `{"type":"array","items":{"type":"string"}}`, "[]string"},
		{"array_of_integer", `{"type":"array","items":{"type":"integer"}}`, "[]int"},
		{"array_of_ref", `{"type":"array","items":{"$ref":"#/definitions/Ref"}}`, "[]Ref"},
		{"array_no_items", `{"type":"array"}`, "[]any"},
		{"array_tuple_items", `{"type":"array","items":[{"type":"string"},{"type":"integer"}]}`, "[]any"},

		// Objects / maps.
		{"map_string", `{"type":"object","additionalProperties":{"type":"string"}}`, "map[string]string"},
		{"map_ref", `{"type":"object","additionalProperties":{"$ref":"#/definitions/Ref"}}`, "map[string]Ref"},
		{"map_addl_true", `{"type":"object","additionalProperties":true}`, "map[string]any"},
		{"free_object", `{"type":"object"}`, "map[string]any"},
		{"pattern_properties", `{"type":"object","patternProperties":{"^x":{"type":"integer"}}}`, "map[string]int"},

		// References.
		{"ref", `{"$ref":"#/definitions/Ref"}`, "*Ref"},

		// enum / const inference.
		{"enum_string", `{"enum":["a","b"]}`, "string"},
		{"enum_number", `{"enum":[1,2]}`, "float64"},
		{"const_string", `{"const":"x"}`, "string"},
		{"const_bool", `{"const":true}`, "bool"},

		// Type unions.
		{"nullable_string", `{"type":["string","null"]}`, "string"},
		{"union_multi", `{"type":["string","integer"]}`, "any"},

		// Constructs with no faithful Go mapping: degrade to any.
		{"oneOf", `{"oneOf":[{"type":"string"},{"type":"integer"}]}`, "any"},
		{"anyOf", `{"anyOf":[{"type":"string"},{"type":"boolean"}]}`, "any"},
		{"not", `{"not":{"type":"string"}}`, "any"},
		{"empty_schema", `{}`, "any"},
		{"boolean_schema_true", `true`, "any"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := optionalFieldType(t, tc.prop); got != tc.want {
				t.Errorf("type for %s = %q, want %q", tc.prop, got, tc.want)
			}
		})
	}
}

// TestGenerateGo_requiredFields verifies that required scalars are value
// types without omitempty and that a required object reference is a value
// (not a pointer).
func TestGenerateGo_requiredFields(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"required": ["name", "ref"],
		"definitions": {"Ref": {"type": "object", "properties": {"a": {"type": "string"}}}},
		"properties": {
			"name": {"type": "string"},
			"opt": {"type": "string"},
			"ref": {"$ref": "#/definitions/Ref"}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema, jsonschema.WithGoRootType("Root"))
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	// A required object reference is a value type, not a pointer.
	if got := structFieldType(t, src, "Root", "Ref"); got != "Ref" {
		t.Errorf("required ref type = %q, want %q", got, "Ref")
	}
	mustContain(t, src,
		"Name string `json:\"name\"`",         // required: no omitempty
		"Opt string `json:\"opt,omitempty\"`", // optional: omitempty
	)
}

// TestGenerateGo_recursive ensures self-referential schemas terminate and
// produce valid Go (the slice breaks the type cycle).
func TestGenerateGo_recursive(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"properties": {"root": {"$ref": "#/definitions/Node"}},
		"definitions": {
			"Node": {
				"type": "object",
				"properties": {
					"value": {"type": "string"},
					"children": {"type": "array", "items": {"$ref": "#/definitions/Node"}}
				}
			}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema)
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src,
		"type Node struct",
		"Children []Node `json:\"children,omitempty\"`",
	)
}

// TestGenerateGo_inlineObjectHoisting checks that an inline object property
// is hoisted into a named type derived from the parent and field names.
func TestGenerateGo_inlineObjectHoisting(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"properties": {
			"server": {
				"type": "object",
				"properties": {"host": {"type": "string"}, "port": {"type": "integer"}}
			}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema, jsonschema.WithGoRootType("Config"))
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	if got := structFieldType(t, src, "Config", "Server"); got != "*ConfigServer" {
		t.Errorf("hoisted field type = %q, want %q", got, "*ConfigServer")
	}
	mustContain(t, src,
		"type ConfigServer struct",
		"Host string `json:\"host,omitempty\"`",
		"Port int `json:\"port,omitempty\"`",
	)
}

// TestGenerateGo_definitionsAndDefs verifies both "definitions" and "$defs"
// yield named types.
func TestGenerateGo_definitionsAndDefs(t *testing.T) {
	schema := []byte(`{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"type": "object",
		"definitions": {"FromDefinitions": {"type": "object", "properties": {"a": {"type": "string"}}}},
		"$defs": {"FromDefs": {"type": "object", "properties": {"b": {"type": "integer"}}}}
	}`)
	src, err := jsonschema.GenerateGo(schema)
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src, "type FromDefinitions struct", "type FromDefs struct")
}

// TestGenerateGo_nonObjectDefinitionAlias verifies that a non-object
// definition becomes a type alias rather than an empty struct.
func TestGenerateGo_nonObjectDefinitionAlias(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"definitions": {
			"ID": {"type": "string"},
			"Ports": {"type": "array", "items": {"type": "integer"}}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema)
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src, "type ID string", "type Ports []int")
}

// TestGenerateGo_keyNamingAndTags checks identifier derivation and that json
// tags preserve the original keys verbatim.
func TestGenerateGo_keyNamingAndTags(t *testing.T) {
	schema := []byte(`{
		"type": "object",
		"properties": {
			"$schema": {"type": "string"},
			"snake_case": {"type": "string"},
			"kebab-case": {"type": "string"},
			"camelCase": {"type": "string"}
		}
	}`)
	src, err := jsonschema.GenerateGo(schema, jsonschema.WithGoRootType("Keys"))
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	mustContain(t, src,
		"Schema string `json:\"$schema,omitempty\"`",
		"SnakeCase string `json:\"snake_case,omitempty\"`",
		"KebabCase string `json:\"kebab-case,omitempty\"`",
		"CamelCase string `json:\"camelCase,omitempty\"`",
	)
}

// TestGenerateGo_options exercises the package name, root type name, and
// header comment options (including suppressing the header).
func TestGenerateGo_options(t *testing.T) {
	schema := []byte(`{"type":"object","properties":{"x":{"type":"string"}}}`)

	src, err := jsonschema.GenerateGo(schema,
		jsonschema.WithGoPackage("custompkg"),
		jsonschema.WithGoRootType("MyRoot"),
		jsonschema.WithGoHeaderComment(""),
	)
	if err != nil {
		t.Fatalf("GenerateGo: %v", err)
	}
	parseGo(t, src)
	got := string(src)
	if !strings.Contains(got, "package custompkg") {
		t.Errorf("missing custom package:\n%s", got)
	}
	if !strings.Contains(got, "type MyRoot struct") {
		t.Errorf("missing custom root type:\n%s", got)
	}
	if strings.Contains(got, "DO NOT EDIT") {
		t.Errorf("header should be suppressed:\n%s", got)
	}
}

// corpus is a set of diverse, valid schemas used to assert that generation
// always yields syntactically valid Go.
var corpus = []string{
	`{"title":"Empty","type":"object"}`,
	`{"type":"object","properties":{"a":{"type":"string"},"b":{"type":"integer"},"c":{"type":"boolean"},"d":{"type":"number"}}}`,
	`{"type":"object","properties":{"list":{"type":"array","items":{"type":"object","properties":{"k":{"type":"string"}}}}}}`,
	`{"type":"object","properties":{"m":{"type":"object","additionalProperties":{"type":"array","items":{"type":"string"}}}}}`,
	`{"type":"object","definitions":{"A":{"allOf":[{"$ref":"#/definitions/B"},{"type":"object","properties":{"x":{"type":"string"}}}]},"B":{"type":"object","properties":{"y":{"type":"integer"}}}}}`,
	`{"type":"object","properties":{"u":{"oneOf":[{"type":"string"},{"type":"integer"}]},"v":{"type":["boolean","null"]}}}`,
	`{"type":"object","properties":{"deep":{"type":"object","properties":{"deeper":{"type":"object","properties":{"x":{"type":"string"}}}}}}}`,
}

// TestGenerateGo_corpusAlwaysValidGo asserts every corpus schema generates
// parseable Go.
func TestGenerateGo_corpusAlwaysValidGo(t *testing.T) {
	for i, s := range corpus {
		src, err := jsonschema.GenerateGo([]byte(s))
		if err != nil {
			t.Errorf("corpus[%d]: GenerateGo: %v", i, err)
			continue
		}
		parseGo(t, src)
	}
}

// FuzzGenerateGo asserts the generator never panics on arbitrary input and,
// whenever it succeeds, emits syntactically valid Go.
func FuzzGenerateGo(f *testing.F) {
	for _, s := range corpus {
		f.Add([]byte(s))
	}
	f.Add([]byte(`{"type":"string"}`))
	f.Add([]byte(`not json`))
	f.Fuzz(func(t *testing.T, data []byte) {
		src, err := jsonschema.GenerateGo(data)
		if err != nil {
			return
		}
		if _, perr := parser.ParseFile(token.NewFileSet(), "gen.go", src, 0); perr != nil {
			t.Fatalf("generated invalid Go for input %q: %v\n%s", data, perr, src)
		}
	})
}
